# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x0b\x41llBookings\x12\x1e\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x0c.UserBooking\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x0bUserBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1b\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x0c.BookingData\"+\n\x0b\x42ookingData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"?\n\x0e\x42ookingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t2\x9b\x01\n\x07\x42ooking\x12\x36\n\x0eGetAllBookings\x12\x16.google.protobuf.Empty\x1a\x0c.AllBookings\x12+\n\x12GetBookingsForUser\x12\x07.UserID\x1a\x0c.UserBooking\x12+\n\nAddBooking\x12\x0f.BookingRequest\x1a\x0c.UserBookingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLBOOKINGS']._serialized_start=46
  _globals['_ALLBOOKINGS']._serialized_end=91
  _globals['_USERID']._serialized_start=93
  _globals['_USERID']._serialized_end=113
  _globals['_USERBOOKING']._serialized_start=115
  _globals['_USERBOOKING']._serialized_end=173
  _globals['_BOOKINGDATA']._serialized_start=175
  _globals['_BOOKINGDATA']._serialized_end=218
  _globals['_BOOKINGREQUEST']._serialized_start=220
  _globals['_BOOKINGREQUEST']._serialized_end=283
  _globals['_BOOKING']._serialized_start=286
  _globals['_BOOKING']._serialized_end=441
# @@protoc_insertion_point(module_scope)
