# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x07\n\x05\x45mpty\"-\n\x0b\x41llBookings\x12\x1e\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x0c.UserBooking\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x0bUserBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1b\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x0c.BookingData\"+\n\x0b\x42ookingData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"?\n\x0e\x42ookingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t2\x8b\x01\n\x07\x42ooking\x12&\n\x0eGetAllBookings\x12\x06.Empty\x1a\x0c.AllBookings\x12+\n\x12GetBookingsForUser\x12\x07.UserID\x1a\x0c.UserBooking\x12+\n\nAddBooking\x12\x0f.BookingRequest\x1a\x0c.UserBookingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_ALLBOOKINGS']._serialized_start=26
  _globals['_ALLBOOKINGS']._serialized_end=71
  _globals['_USERID']._serialized_start=73
  _globals['_USERID']._serialized_end=93
  _globals['_USERBOOKING']._serialized_start=95
  _globals['_USERBOOKING']._serialized_end=153
  _globals['_BOOKINGDATA']._serialized_start=155
  _globals['_BOOKINGDATA']._serialized_end=198
  _globals['_BOOKINGREQUEST']._serialized_start=200
  _globals['_BOOKINGREQUEST']._serialized_end=263
  _globals['_BOOKING']._serialized_start=266
  _globals['_BOOKING']._serialized_end=405
# @@protoc_insertion_point(module_scope)
