# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showtime.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'showtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\",\n\x0cShowtimeData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"2\n\x0f\x41llShowtimeData\x12\x1f\n\x08schedule\x18\x01 \x03(\x0b\x32\r.ShowtimeData2t\n\x08Showtime\x12=\n\x0fGetAllShowtimes\x12\x16.google.protobuf.Empty\x1a\x10.AllShowtimeData\"\x00\x12)\n\x0fGetMoviesByDate\x12\x05.Date\x1a\r.ShowtimeData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATE']._serialized_start=47
  _globals['_DATE']._serialized_end=67
  _globals['_SHOWTIMEDATA']._serialized_start=69
  _globals['_SHOWTIMEDATA']._serialized_end=113
  _globals['_ALLSHOWTIMEDATA']._serialized_start=115
  _globals['_ALLSHOWTIMEDATA']._serialized_end=165
  _globals['_SHOWTIME']._serialized_start=167
  _globals['_SHOWTIME']._serialized_end=283
# @@protoc_insertion_point(module_scope)
